// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/index.jsx";
import * as $1 from "./routes/random/index.jsx";
import * as $2 from "./routes/search/[search].jsx";
import * as $3 from "./routes/search/index.jsx";
import * as $4 from "./routes/vn/[id].jsx";

const manifest = {
  routes: {
    "./routes/index.jsx": $0,
    "./routes/random/index.jsx": $1,
    "./routes/search/[search].jsx": $2,
    "./routes/search/index.jsx": $3,
    "./routes/vn/[id].jsx": $4,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
